#!/usr/bin/env python3
import os
import sys
import argparse
from openai import OpenAI

def parse_trace_file(file_path, top_n=5):
    if not os.path.exists(file_path):
        print(f"Error: Trace file '{file_path}' not found.")
        sys.exit(1)

    trace_summary = []
    with open(file_path, 'r') as f:
        lines = f.readlines()

    start_idx = 0
    for i, line in enumerate(lines):
        if line.startswith("---------"):
            start_idx = i + 1
            break

    for line in lines[start_idx:]:
        stripped = line.strip()
        if not stripped or stripped.startswith("====="):
            break 

        parts = stripped.split()
        if len(parts) < 3:
            continue

        instructions = parts[0]
        percentage = parts[1].rstrip('%')
        func_name = parts[-1]
        
        if func_name == '%': continue 
        if func_name.startswith('%'): func_name = func_name[1:]

        trace_summary.append({
            "instructions": instructions,
            "percentage": percentage + "%",
            "function": func_name
        })

    return trace_summary[:top_n]


def generate_optimization_suggestions(trace_data, benchmark_name=None):
    client = OpenAI()
    context = f" The benchmark is '{benchmark_name}' from the MiBench suite." if benchmark_name else ""

    prompt = (
        "You are an expert C/C++ performance engineer and compiler architect. "
        "Analyze the following flat profile generated by a custom Intel PIN "
        f"dynamic instrumentation tool.{context}\n\n"
        "Top CPU-Intensive Functions (Bottlenecks):\n"
    )

    for i, data in enumerate(trace_data, 1):
        prompt += f"{i}. `{data['function']}` — Accounts for {data['percentage']} of total execution ({data['instructions']} instructions)\n"

    prompt += (
        "\nBased on the function signatures and their execution weight, provide a structured report covering:\n"
        "1. **Architectural & Algorithmic Diagnosis**: What are the likely causes of high instruction counts in these specific functions?\n"
        "2. **Code-Level Optimizations**: Suggest specific C/C++ techniques to reduce the instruction footprint (e.g., better algorithms, loop unrolling, vectorization).\n"
        "3. **Memory & Data Structure Considerations**: Suggest alternatives that might improve cache locality or reduce memory access overhead.\n"
        "4. **Estimated Impact**: For each suggestion, estimate the potential instruction count reduction.\n"
        "Keep the advice highly technical, actionable, and specific to C/C++ workloads."
    )

    print("  Sending trace data to LLM for architectural analysis...\n")
    try:
        response = client.chat.completions.create(
            model="gpt-4o",
            messages=[
                {"role": "system", "content": "You are an expert C/C++ systems performance profiler."},
                {"role": "user", "content": prompt}
            ],
            temperature=0.2
        )
        return response.choices[0].message.content
    except Exception as e:
        return f"Error communicating with the AI model: {e}"


def main():
    parser = argparse.ArgumentParser(description="LLM-Augmented Performance Profiler — Analyzer")
    parser.add_argument("-t", "--trace", required=True, help="Path to the trace file generated by the PIN tool")
    parser.add_argument("-n", "--top", type=int, default=5, help="Number of top functions to analyze")
    parser.add_argument("-b", "--bench", default=None, help="Benchmark name")
    parser.add_argument("-o", "--out", default=None, help="Path to save the AI report")
    args = parser.parse_args()

    print(f"  Reading performance trace: {args.trace}")
    top_functions = parse_trace_file(args.trace, top_n=args.top)

    if not top_functions:
        print("  No valid trace data found. Check your PIN tool output format.")
        sys.exit(1)

    suggestions = generate_optimization_suggestions(top_functions, args.bench)
    
    output_path = args.out if args.out else "ai_optimization_report.md"

    print("\n" + "=" * 80)
    print(" 🚀 AI AUTOMATED OPTIMIZATION REPORT")
    if args.bench: print(f"    Benchmark: {args.bench}")
    print("=" * 80)
    print(suggestions)
    print("=" * 80)

    os.makedirs(os.path.dirname(output_path) or '.', exist_ok=True)
    with open(output_path, "w") as f:
        header = f"# AI Optimization Report" + (f" — {args.bench}" if args.bench else "")
        f.write(header + "\n\n")
        f.write(suggestions)

    print(f"\n  📄 Report saved to: {output_path}")

if __name__ == "__main__":
    main()